### ISSUE TITLE
Fix the "hacky" solutions to the integration problems

### ISSUE THREAD

**Issue by theoxo** [mrbenshef/SmartHomeAdapters#111]
We had to hack some stuff together today, such as:

- Stripping spaces from parameter names when sending them back to the server
- Casting use case names to lower case when registering a robot

We should find more elegant solutions for this.

**Comment by mrbenshef** [comment]
Fixed in #149

**Comment by theoxo** [comment]
@mrbenshef Specifically which changes does this address? (So I know what to change on the app side)

**Comment by mrbenshef** [comment]
I hadn’t read this issue properly! #149 adds ID’s to the parameter names. I’ll take a look at usecases in a bit.

**Comment by mrbenshef** [comment]
Kind of fixed :P
